M48
; DRILL file KiCad 10.0.5 date 2026-08-23T18:21:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-23T18:21:08-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X253.285Y-92.31
X253.285Y-98.09
T2
X251.6Y-109.19
X251.6Y-130.78
M30
